export const careerRecord = {
  updated: "2026.08",
  profile: {
    name: "飯野 海斗",
    experience: "IT業界 約7年",
    form: "KiT Works / 個人事業主",
    focus: "AI・RAG / PM・PMO / PL / ソフトウェア開発",
  },
  summary:
    "2019年からIT業界で約7年。C/C++を中心とした車載・組み込み開発、Pythonによるデータ処理・クラウド連携、ログ管理基盤移行を経験したうえで、PL、顧客折衝、要件・仕様策定、PMO、成果物品質管理・トレーサビリティ管理へ担当範囲を拡大。2026年5月にKiT Worksとして独立し、現在は大手製造業向けのAI/RAG活用・AI製品開発と、AI-PMプロジェクトのPM・開発推進に従事しています。",
  strengths: [
    {
      number: "01",
      title: "PM / PL / プロジェクト推進",
      lead: "進捗、課題、品質、成果物、会議体を整理し、プロジェクトが前に進む状態を整えます。",
      points: ["5名チームのタスク管理", "Jiraでのチケット作成・担当割り振り・進捗確認", "週次報告・リーダー会資料作成", "顧客折衝・合意形成"],
    },
    {
      number: "02",
      title: "成果物品質 / トレーサビリティ",
      lead: "基本設計、要求仕様書、要件定義書、画面仕様書などの成果物品質と整合性を確認します。",
      points: ["成果物レビュー・監査", "トレーサビリティ作成・管理・監査", "レビュー観点整理", "作成チームへのフィードバック"],
    },
    {
      number: "03",
      title: "要件整理 / 顧客折衝 / 仕様策定",
      lead: "曖昧な要望を、仕様、設計、タスク、テスト観点へ落とし込みます。",
      points: ["国内外担当者との仕様調整", "要件定義・仕様策定", "設計からテストまでの一貫対応", "認識齟齬・手戻りの抑制"],
    },
    {
      number: "04",
      title: "AI / RAG / 仕様書探索",
      lead: "生成AIを単体利用で終わらせず、検索、評価、業務フローまで含めて実務へ組み込みます。",
      points: ["RAG型仕様書チャットボット", "LangChain / LangGraph / MCP", "Box連携検索・Slack要約", "AI出力の再現性・品質安定化"],
    },
    {
      number: "05",
      title: "車載 / 組み込み開発",
      lead: "C/C++を中心に、車載・組み込み領域で要件定義から評価まで経験しています。",
      points: ["AUTOSAR準拠DIAG機能", "CANoe / DaVinci", "MATLAB / Simulink", "ドライバ開発・結合試験設計"],
    },
    {
      number: "06",
      title: "Python / データ / ログ",
      lead: "Pythonによるデータ処理、AWS連携、ログ管理基盤移行、監視・可視化設計を経験しています。",
      points: ["Pythonデータ抽出・分析", "AWSクラウド転送", "Datadog → Splunk移行", "SPL変換・ダッシュボード・アラート設計"],
    },
  ],
  employments: [
    {
      period: "2019/04 - 2022/04",
      company: "PCIソリューションズ株式会社",
      role: "エンベデッドソリューション事業部",
      summary: "車載・組み込み、ネットワーク機器、ストレージ製品、AUTOSAR開発に従事。開発メンバーからプロジェクトリーダーまで経験。",
    },
    {
      period: "2022/04 - 2026/04",
      company: "アルテンジャパン株式会社",
      role: "技術コンサルティング職 / ITコンサルティング職",
      summary: "決済、車載、ログ管理基盤、製造業向け開発支援を経験。後半はPMO、成果物確認・検収、トレーサビリティ、品質・プロセス改善を担当。",
    },
    {
      period: "2026/05/01 - 現在",
      company: "KiT Works",
      role: "個人事業主",
      summary: "AI/RAG活用、AI製品開発、PM・開発推進を中心に業務を実施。大手製造業向けAI業務とAI-PMプロジェクトに参画。",
    },
  ],
  experiences: [
    {
      number: "01",
      period: "2026/08 - 現在",
      title: "AI-PMプロジェクト推進・開発",
      domain: "AI / プロダクト開発 / PM",
      role: "PM / 開発推進",
      overview: "PM業務のうち、関係者間のハブ機能や進捗・方針整理など高負荷な領域をAIで支援するAI-PMプロジェクト。",
      scope: "現場進捗・方針・期限の整理、既存設計の把握、エグゼクティブ向け設計整理、ロードマップ検討、プロトタイピング方針、Gitリポジトリ共有・開発推進を担当。",
      result: "PMと開発のハブとしてプロジェクトを推進中。フェーズ1に向けた方針・ロードマップ・設計整理を進めています。",
      tools: ["Git", "生成AI", "AI-PM", "設計ドキュメント", "プロトタイピング"],
    },
    {
      number: "02",
      period: "2026/05 - 現在",
      title: "大手製造業向け AI/RAG活用・AI製品開発支援",
      domain: "製造 / 自動車・車載 / AI",
      role: "AI活用支援 / RAG設計・構築 / AI案件PM",
      overview: "大手製造業の開発現場で、仕様書探索、生成AI活用、AI製品開発を支援。独立後のCSC関連業務ではAI領域を担当。",
      scope: "Excel仕様書、要求仕様書、要件定義書、画面仕様書を対象に、LangChain / LangGraphによるRAG、参照範囲制御、Box連携検索、Slack要約、プロンプト調整、回答品質評価を実施。5名体制のAI案件PM、Jira連携の進行管理・WBS支援ツール内製、AI駆動開発ワークショップの企画・主催にも対応。",
      result: "仕様探索・確認業務の効率化、複数PJへの展開、AI出力の再現性・品質安定化、PoCから業務適用までの推進を支援。",
      keyWorks: [
        {
          number: "01",
          title: "RAG型仕様書チャットボット構築・生成AI活用支援",
          role: "AI活用支援 / RAG設計・構築 / 回答品質改善",
          issue: "Excel仕様書、要求仕様書、要件定義書、画面仕様書を横断して確認する負荷が高く、仕様探索を業務フローに組み込む必要があった。既存のRAG機能では、資料形式やフォルダ構成が統一されていない資料群を広く検索し、質問に不要な情報まで参照される状態だった。",
          scope: "LangChainを活用したRAG構成、検索対象資料の整理、チャンク分割方針、Box連携検索、Slack要約、プロンプト調整を担当。LangGraphを用いて質問内容に応じた参照資料・情報範囲の絞り込みと、後続ワークフローへの受け渡しを設計。",
          result: "検索対象と回答生成時に扱う情報を分離し、不要な情報が回答へ混ざりにくい構成へ改善。仕様探索・確認業務の効率化、複数PJへの展開、レビュー観点整理、AI活用時の再現性・品質安定化を支援。",
          tools: ["RAG", "LangChain", "LangGraph", "参照範囲の制御", "MCP", "Box連携検索", "Slack/API連携", "ローカルLLM", "AGENTS.md", "Skills"],
        },
        {
          number: "02",
          title: "生成AIチャットボット開発プロジェクトのPM（PoC〜業務適用）",
          role: "AI案件PM / 5名チーム運営 / 顧客折衝",
          issue: "顧客側でAI導入が進んでおらず、生成AIを用いた製品に対して当初から懐疑的な見方があり、要望のたびに実現可能性を問われる状況だった。",
          scope: "5名チームのPMとして、プロトタイプ試作、顧客要望の改良案出し、チャットボット本体実装、精度検証を、状況に応じて役割配置。細かい要求ごとに試作で実現可能性を提示し、Jiraで進捗を管理しながら次回顧客会議で提示可能な状態を判断基準として運営。",
          result: "PoCから業務適用・訴求段階まで一連の推進を担当。要望整理、優先順位付け、課題管理を顧客会議の周期に合わせて回し、懐疑的な状態から実業務での利用検討まで進めた。",
          tools: ["AI案件PM", "PoC / プロトタイピング", "アジャイル運営", "顧客折衝", "要望整理・優先度付け", "Jira", "5名チーム"],
        },
        {
          number: "03",
          title: "生成AIによる進行管理・WBS運用ツールの内製",
          role: "企画 / 設計・実装 / 運用設計",
          issue: "週2回の顧客会議ごとに要望や優先度が変化し、Jiraのチケット運用だけでは変更の検知や期限・リスクの把握が遅れる懸念があった。",
          scope: "JiraチケットのCSV出力とAIで作成した会議議事録を入力に、要望変更、優先度変更の可能性、期限・リスクの高い項目を抽出するツールを内製。出力担当LLMの結果を評価担当LLMが確認し、抜け漏れ・矛盾・根拠との不一致をフィードバックするセルフリフレクションを複数回通し、結果をSlack通知する運用を設計。",
          result: "Jiraの自動更新や優先度の自動確定は行わず、確認候補の抽出と注意喚起に限定。精度検証担当が元チケットと会議合意に照らして確認し、人が最終判断する二段構えとして、誤ったリマインドと対応漏れによる遅延を防いだ。",
          tools: ["生成AI内製ツール", "Jira連携（CSV）", "議事録自動生成", "セルフリフレクション", "評価LLM", "Slack通知", "WBS / 進行管理"],
        },
        {
          number: "04",
          title: "生成AI活用推進ワークショップの企画・主催",
          role: "企画 / 主催・進行 / 指南",
          issue: "参画先の開発IDE製品をその先の顧客へ訴求するにあたり、AI駆動開発の効果が体感されておらず、現場でのAI活用も定着していなかった。",
          scope: "開発IDE製品を題材に、AI駆動開発（バイブコーディング）を実際に体験できるワークショップを企画・主催。プロンプトの粒度が最終成果物の精度へどう影響するかを、その場で比較・体感できる進め方を設計し、操作手順と勘所を指南。",
          result: "参加者が製品上でAI駆動開発の効果を体験できる場をつくり、現場へのAI活用推進と製品訴求の双方に貢献。",
          tools: ["AI駆動開発", "バイブコーディング", "プロンプト粒度設計", "ワークショップ企画・主催", "活用推進", "製品訴求"],
        },
      ],
      tools: ["RAG", "LangChain", "LangGraph", "MCP", "Box", "Slack", "Jira", "ChatGPT", "Anthropic Claude", "Codex", "Claude Code", "AGENTS.md", "Skills"],
    },
    {
      number: "03",
      period: "2024/12 - 2026/04",
      title: "大手製造業向け 開発プロセス適用・成果物監査・PMO支援",
      domain: "製造 / 自動車・車載 / PMO",
      role: "チームリード / PMO支援 / 成果物品質管理",
      overview: "大手製造業向け開発案件で、開発プロセス、成果物品質、進捗・課題管理を整理し、プロジェクト推進を支援。",
      scope: "5名チームのタスク管理、基本設計・要求仕様書・要件定義書・画面仕様書の成果物確認、トレーサビリティ作成・管理・監査、Jiraでの進捗管理、週次報告、作成チームへのフィードバックを担当。",
      result: "進捗・課題の可視化、成果物品質確認、プロセス標準化、チーム運営を支援。",
      tools: ["Jira", "Slack", "Confluence", "VSCode", "PlantUML"],
    },
    {
      number: "04",
      period: "2024/04 - 2024/11",
      title: "大手輸送用機器メーカー向けマウンター機開発",
      domain: "製造 / 輸送用機器",
      role: "開発担当 / 顧客折衝・仕様策定",
      overview: "顧客要望を実装可能な仕様へ落とし込み、C++とC#間のデータ連携処理を開発。",
      scope: "顧客要望の整理、仕様策定、設計、実装、テストを担当。C++とC#間のデータコンバート処理について、仕様理解から実装・動作確認まで対応。",
      result: "仕様合意から実装・検証まで一連の開発を担当し、顧客側と開発側の認識合わせを推進。",
      tools: ["C++", "C#", "Redmine", "Visual Studio", "BitBucket", "Slack", "Teams", "Lightning Review"],
    },
    {
      number: "05",
      period: "2023/12 - 2024/03",
      title: "統合ログ管理プラットフォーム導入支援",
      domain: "IT / ログ管理 / 監視基盤",
      role: "データエンジニア / 導入支援",
      overview: "DatadogからSplunkへのログ管理基盤移行を支援。",
      scope: "既存Datadogクエリの解析、Splunk SPLへの変換、ダッシュボードおよびアラート機能の設計・実装を主導。",
      result: "移行後も監視・可視化を継続できる状態を整備。",
      tools: ["Splunk", "Datadog", "SPL", "DQL", "Amazon WorkSpaces"],
    },
    {
      number: "06",
      period: "2022/07 - 2023/11",
      title: "カーナビシステムのラジオ機能開発",
      domain: "自動車 / 車載 / 組み込み",
      role: "開発担当 / 顧客折衝",
      overview: "国内および北欧向けカーナビのラジオ機能開発。",
      scope: "国内外担当者との仕様策定・調整、C/C++による設計・実装・テスト、CANoe等を用いた動作確認を担当。",
      result: "認識齟齬を抑えながら、顧客要望を実装可能な仕様へ落とし込み、実装・検証まで対応。",
      tools: ["C", "C++", "git", "VSCode", "CANoe", "VirtualBox"],
    },
    {
      number: "07",
      period: "2022/04 - 2022/06",
      title: "大手決済代行会社のシステム導入支援",
      domain: "金融 / 決済",
      role: "開発メンバー",
      overview: "大手決済代行会社のシステム導入案件で、売上分析システムの導入を支援。",
      scope: "Confluenceを用いた開発プロセスの設計・確立、作業手順整理、Pythonによるデータ抽出・分析スクリプト作成を担当。",
      result: "導入作業の手順とプロセスを整備し、データ抽出・分析作業を支援。",
      tools: ["Python", "Confluence"],
    },
    {
      number: "08",
      period: "2021/08 - 2022/04",
      title: "画像センサ開発（AUTOSAR）",
      domain: "自動車 / 車載 / 組み込み",
      role: "プロジェクトリーダー",
      overview: "AUTOSAR準拠の次世代画像センサ開発でDIAG機能を担当。",
      scope: "メンバーのタスク管理、進捗管理、技術フォローを行いながら、DIAG機能の要件定義、設計、実装、評価まで一貫して担当。",
      result: "技術面と管理面の両方から開発を推進し、要件定義から評価まで完遂。",
      tools: ["C", "AUTOSAR", "CANoe", "DaVinci Configurator", "DaVinci Developer", "Subversion", "git", "Redmine"],
    },
    {
      number: "09",
      period: "2021/01 - 2021/07",
      title: "ストレージ製品のクラウド連携機能開発",
      domain: "ストレージ / クラウド連携",
      role: "開発メンバー",
      overview: "Linuxベースのストレージ製品からAWSクラウドへデータを転送する新機能を開発。",
      scope: "Pythonを用いたAWSクラウド転送機能の設計・実装、Linux環境での状態監視、性能モニタ評価、データ転送処理の確認を担当。",
      result: "クラウド転送、状態確認、性能確認を含む連携機能の開発・検証に対応。",
      tools: ["Python", "Linux", "AWS", "git", "VirtualBox"],
    },
    {
      number: "10",
      period: "2020/07 - 2020/12",
      title: "ネットワーク機器開発",
      domain: "通信 / ネットワーク機器",
      role: "開発メンバー",
      overview: "キャリア / エンタープライズ向けハイエンドルータ・スイッチの制御ソフトウェア開発。",
      scope: "Debian環境でC言語による40G/100Gイーサネット対応の新機能開発、品質改善、不具合修正、不具合解析を担当。",
      result: "新機能開発と品質改善、不具合解析・修正に対応。",
      tools: ["C", "Debian", "git", "GDB", "Jira", "Subversion"],
    },
    {
      number: "11",
      period: "2020/05 - 2020/06",
      title: "ボディ系ECU制御開発 / モデル検証",
      domain: "自動車 / 車載 / モデルベース開発",
      role: "開発メンバー",
      overview: "モデルベース開発におけるECU制御モデルの品質保証業務。",
      scope: "SimulinkモデルのBack-to-Back検証、MATLABによる試験ハーネス作成とテスト実行を担当。",
      result: "モデルと実装結果の整合性確認、テスト実行による品質検証に対応。",
      tools: ["MATLAB", "Simulink"],
    },
    {
      number: "12",
      period: "2020/04",
      title: "AWSおよびモデルベース開発研修",
      domain: "研修 / Cloud / MBD",
      role: "研修生",
      overview: "AWSとモデルベース開発の基礎研修。",
      scope: "AWS主要サービスの基礎、MATLAB / Simulinkによるモデルベース開発の基礎を習得。",
      result: "クラウドおよびモデルベース開発の基礎知識を習得。",
      tools: ["AWS", "MATLAB", "Simulink"],
    },
    {
      number: "13",
      period: "2019/09 - 2020/03",
      title: "カーナビゲーション開発",
      domain: "自動車 / 車載",
      role: "開発メンバー",
      overview: "車載向けカーナビゲーションの通信機能開発。",
      scope: "コンフィグレーション設定資料作成、FBL-SPI通信ドライバ開発、単体テスト、FBL-Diag結合試験設計、CAN通信結合試験を担当。",
      result: "通信機能の実装から単体・結合試験まで一連の工程に対応。",
      tools: ["C", "Visual Studio"],
    },
    {
      number: "14",
      period: "2019/04 - 2019/08",
      title: "新入社員向け技術研修",
      domain: "研修 / 組み込み",
      role: "研修生 / プロジェクト演習PM",
      overview: "C/C++、Linux、組み込み・車載開発の基礎研修。",
      scope: "C/C++、Linux、オブジェクト指向、μITRON、AUTOSAR概論、TOPPERS/ATK2を用いたモデルカー開発演習に取り組み、プロジェクト演習ではPMとして進行整理を経験。",
      result: "組み込み開発の基礎技術と、チーム演習での進行管理を習得。",
      tools: ["C", "C++", "Linux", "μITRON", "AUTOSAR", "TOPPERS/ATK2"],
    },
  ],
  activities: [
    {
      title: "AI駆動開発の登壇経験",
      body: "AIを用いた自作アプリ開発について登壇。個人事業の経理簡略化・自動化を目的とした簡易アプリを、Codex、Google Drive、Claude Codeを用いて開発した事例を発表。",
      tools: ["Codex", "Google Drive", "Claude Code"],
    },
    {
      title: "海外会議向け通訳・翻訳支援ツール",
      body: "海外担当者・英語話者との会議時に、生成AI、翻訳・音声関連ツール、API連携を用いた通訳・翻訳支援ツールを実装し、会議理解と言語面の負荷軽減を支援。",
      tools: ["生成AI", "翻訳・音声関連ツール", "API連携"],
    },
    {
      title: "ローカルLLMの業務適用検証",
      body: "クラウド型AIだけでなくローカル環境でのLLM利用も検証し、業務適用可能性を確認。",
      tools: ["HuggingFace", "Qwen", "ローカルLLM"],
    },
    {
      title: "資料作成・調査・論点整理への生成AI活用",
      body: "資料作成、調査、要約、論点整理、レビュー観点整理に生成AIを活用し、調査・レビュー業務の効率化を支援。",
      tools: ["ChatGPT", "Copilot", "Anthropic Claude"],
    },
  ],
  skills: [
    { title: "AI / RAG / Automation", skills: ["RAG", "LangChain", "LangGraph", "MCP", "ChatGPT", "Copilot", "Anthropic Claude", "Codex", "Claude Code", "HuggingFace", "Qwen", "ローカルLLM", "API連携", "Box連携検索", "Slack要約", "評価LLM", "セルフリフレクション", "AGENTS.md", "Skills", "プロンプト設計", "AI駆動開発", "PlantUML"] },
    { title: "PM / Collaboration / Quality", skills: ["AI案件PM", "PMO", "PL", "WBS / 進行管理", "Jira", "Confluence", "Slack", "Teams", "Redmine", "BitBucket", "Lightning Review", "成果物監査", "トレーサビリティ"] },
    { title: "Programming", skills: ["C", "C++", "Python", "C#", "Java基礎"] },
    { title: "Data / Log / Cloud", skills: ["AWS", "Amazon WorkSpaces", "Splunk", "Datadog", "SPL", "DQL", "Linux"] },
    { title: "Embedded / Automotive", skills: ["AUTOSAR", "CANoe", "DaVinci Configurator", "DaVinci Developer", "MATLAB", "Simulink", "μITRON", "TOPPERS/ATK2"] },
    { title: "Development Tools", skills: ["git", "Subversion", "GDB", "Visual Studio", "VSCode", "VirtualBox"] },
    { title: "Web / CMS", skills: ["WordPress", "HTML", "CSS", "JavaScript", "SEOメタ情報", "OGP", "sitemap.xml", "robots.txt"] },
  ],
  qualifications: [
    "GUGA Generative AI Passport — 2025年10月認定",
    "AWS Partner: Accreditation — 2020年4月取得",
    "TOEIC公開テスト 510点 — 2019年3月取得 / 英語: 基礎〜日常会話レベル",
  ],
  selfPr: [
    "車載・組み込み開発で培った実装経験を土台に、要件整理、仕様策定、設計、実装、テスト、評価まで、開発現場の工程を理解したうえでプロジェクトを支援できます。",
    "顧客折衝や国内外担当者との仕様調整を含む案件を複数経験しており、曖昧な要望を仕様、設計、タスク、テスト観点に落とし込むことを得意としています。",
    "PMO / PL領域では、進捗・課題管理、成果物監査、品質向上支援、会議体運営、チームメンバーのタスク管理、トレーサビリティ作成・管理・監査を経験しています。",
    "近年はRAG、LangChain、LangGraph、MCP、Box連携検索、Slack要約、AGENTS.md、Skills、プロンプト設計などを活用し、開発現場の実務理解とAI活用の両面から、プロジェクト推進、プロセス改善、業務効率化に取り組んでいます。",
  ],
} as const;
